### ISSUE TITLE
songrequests example

### ISSUE THREAD

**Issue by SystemChanger** [teamrevlo/revlo-python-client#5]
I am trying to use your songrequests example and did everything from the Install Instructions, all things run well, but the message "Sending message: PRIVMSG CHANNEL_NAME :!songs request SONG_LINK" is not going from the IRC to chat on twitch.
I am new with python and impressed by that Revlo-feature and want it to work.
Am i doing smth wrong? Help please)

**Comment by scottnguyen** [comment]
I need more info on your `config.yml` but leave out sensitive data like `API_KEY`.

If you want something more user friendly, try using HugoBullont's implementation in C#: https://github.com/hugobullont/RevloClient

**Comment by JasonMcRay** [comment]
I am having similiar issue. When I start it up i get this:
```Traceback (most recent call last):
  File ".\song_requests.py", line 57, in <module>
    main()
  File ".\song_requests.py", line 37, in main
    twitch = config['twitch']
TypeError: list indices must be integers or slices, not str
```

Here is my config.yml:
```
- revlo:
  api_key: API_REVLO
  reward_id: 527548

- twitch:
  password: OAUTH_TWITCH
  channel: jasonmcray
  username: jasonmcray
  server: irc.chat.twitch.tv
  port: 6667
```

**Comment by scottnguyen** [comment]
Thanks. I tried this on a Windows box and was able to repro the situation. It looks like PyYAML isn't consistent on Windows versus Linux and OSX. Remove the dashes and it should start working. It should look something like this:
```
revlo:
  api_key: API_REVLO
  reward_id: 527548

twitch:
  password: OAUTH_TWITCH
  channel: jasonmcray
  username: jasonmcray
  server: irc.chat.twitch.tv
  port: 6667
```

Let me know if that works for you.

**Comment by JasonMcRay** [comment]
Yup. It started to work. What a simple fix it was. Thank you :D

**Comment by SystemChanger** [comment]
Scott, still not working. (Message just not shown in twitch chat, but the points going out and i am receiving the message "Sending message to..." in the shell)

Here is config.yml:
```
revlo:
  api_key: MY_KEY
  reward_id: 470175

twitch:
  password: MY_OAUTH
  channel: System_Changer
  username: System_Changer
  server: irc.chat.twitch.tv
  port: 6667
```
Using windows 10.

Sometimes earlier messages were send and everything works, but some of them were "eaten" and not displayed in chat. Now they r all "eaten" =D
